# Generated by Django 5.2.12 on 2026-03-29 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
        ('products', '0002_remove_product_stock_inventory_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='merchant',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'MERCHANT'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='min_product_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum price per product to apply discount (e.g., 100 for "Buy 100+ get 20 off")', max_digits=10),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Leave empty for all products, or select specific products', related_name='discount_codes', to='products.product'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='discountcode',
            unique_together={('merchant', 'code')},
        ),
    ]
