# Generated by Django 5.2.12 on 2026-04-09 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_returnrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnrequest',
            name='order',
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='order_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_request', to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REFUNDED', 'Refunded')], default='REQUESTED', max_length=20),
        ),
    ]
